-- ==================================================================================
-- FULL DATABASE SCHEMA - SQL SERVER
-- All table names are lowercase and prefixed with 'rp_'
-- IDs are VARCHAR(36) to support UUIDs generated by the application
-- ==================================================================================

-- 1. Drop existing tables if they exist (Reverse order of dependencies)
IF OBJECT_ID('rp_template_query_mapping', 'U') IS NOT NULL DROP TABLE rp_template_query_mapping;
IF OBJECT_ID('rp_report_template_version', 'U') IS NOT NULL DROP TABLE rp_report_template_version;
IF OBJECT_ID('rp_report_template', 'U') IS NOT NULL DROP TABLE rp_report_template;
IF OBJECT_ID('rp_report_query_placeholder_metadata', 'U') IS NOT NULL DROP TABLE rp_report_query_placeholder_metadata;
IF OBJECT_ID('rp_report_query', 'U') IS NOT NULL DROP TABLE rp_report_query;
IF OBJECT_ID('rp_report_connector', 'U') IS NOT NULL DROP TABLE rp_report_connector;

-- 2. Create Tables

-- 2.1 Report Connectors (Connector-Query Service)
CREATE TABLE rp_report_connector (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    db_type VARCHAR(50) NOT NULL, -- SQL_SERVER, MYSQL, POSTGRESQL, ORACLE
    jdbc_url VARCHAR(500) NOT NULL,
    host VARCHAR(255),
    port INT,
    db_name VARCHAR(100),
    use_raw_url BIT DEFAULT 0,
    username VARCHAR(100) NOT NULL,
    password_encrypted VARCHAR(MAX),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE()
);

-- 2.2 Report Queries (Connector-Query Service)
CREATE TABLE rp_report_query (
    id VARCHAR(36) PRIMARY KEY,
    connector_id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    query_text NVARCHAR(MAX) NOT NULL,
    description VARCHAR(500),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT FK_Query_Connector FOREIGN KEY (connector_id) REFERENCES rp_report_connector(id)
);

-- 2.3 Query Placeholder Metadata (@ElementCollection)
CREATE TABLE rp_report_query_placeholder_metadata (
    query_id VARCHAR(36) NOT NULL,
    placeholder_name VARCHAR(100) NOT NULL,
    data_type VARCHAR(50),
    description VARCHAR(500),
    PRIMARY KEY (query_id, placeholder_name),
    CONSTRAINT FK_Metadata_Query FOREIGN KEY (query_id) REFERENCES rp_report_query(id) ON DELETE CASCADE
);

-- 2.4 Report Templates (Report Service)
CREATE TABLE rp_report_template (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE()
);

-- 2.5 Report Template Versions (Report Service)
CREATE TABLE rp_report_template_version (
    id VARCHAR(36) PRIMARY KEY,
    template_id VARCHAR(36) NOT NULL,
    version_number INT NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    created_by VARCHAR(100),
    is_active INT NOT NULL DEFAULT 0, -- 0: Inactive, 1: Active
    created_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT FK_Version_Template FOREIGN KEY (template_id) REFERENCES rp_report_template(id) ON DELETE CASCADE
);

-- 2.6 Template Query Mapping (Report Service)
CREATE TABLE rp_template_query_mapping (
    id VARCHAR(36) PRIMARY KEY,
    template_version_id VARCHAR(36) NOT NULL,
    query_id VARCHAR(36) NOT NULL,
    query_name VARCHAR(255),
    connector_id VARCHAR(36),
    connector_name VARCHAR(255),
    connector_db_type VARCHAR(50),
    json_node_name VARCHAR(100) NOT NULL, -- e.g. "salesData"
    created_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT FK_Mapping_Version FOREIGN KEY (template_version_id) REFERENCES rp_report_template_version(id) ON DELETE CASCADE,
    CONSTRAINT UQ_Version_Node UNIQUE (template_version_id, json_node_name)
);

-- 3. Indexes
CREATE INDEX IDX_Query_Conn ON rp_report_query(connector_id);
CREATE INDEX IDX_Meta_Query ON rp_report_query_placeholder_metadata(query_id);
CREATE INDEX IDX_Ver_Temp ON rp_report_template_version(template_id);
CREATE INDEX IDX_Map_Ver ON rp_template_query_mapping(template_version_id);

-- ==================================================================================
-- SAMPLE DATA
-- ==================================================================================

-- Sample Connector
INSERT INTO rp_report_connector (id, name, db_type, jdbc_url, username, password_encrypted)
VALUES ('c1a2b3c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 'Production Sales DB', 'SQL_SERVER', 'jdbc:sqlserver://prod-db:1433;databaseName=Sales', 'report_user', 'ENC(some-encrypted-pass)');

-- Sample Query
INSERT INTO rp_report_query (id, connector_id, name, query_text, description)
VALUES ('q9z8y7x6-5w4v-3u2t-1s0r-q9p8o7n6m5l4', 'c1a2b3c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 'Monthly Sales Report', 'SELECT region, sum(amount) as total FROM sales WHERE month = :monthValue GROUP BY region', 'Fetches Regional Sales Summary');

-- Query Placeholders
INSERT INTO rp_report_query_placeholder_metadata (query_id, placeholder_name, data_type, description)
VALUES ('q9z8y7x6-5w4v-3u2t-1s0r-q9p8o7n6m5l4', 'monthValue', 'INTEGER', 'The month to report (1-12)');

-- Sample Template
INSERT INTO rp_report_template (id, name, description)
VALUES ('t1122334-4455-6677-8899-00aabbccddee', 'Standard Monthly Sales Template', 'Word template for regional monthly sales');

-- Sample Template Version (Active)
INSERT INTO rp_report_template_version (id, template_id, version_number, storage_path, created_by, is_active)
VALUES ('v1122334-4455-6677-8899-00aabbccddee', 't1122334-4455-6677-8899-00aabbccddee', 1, 'templates/t1_v1.docx', 'admin', 1);

-- Sample Mapping
INSERT INTO rp_template_query_mapping (id, template_version_id, query_id, query_name, json_node_name)
VALUES ('m1122334-4455-6677-8899-00aabbccddee', 'v1122334-4455-6677-8899-00aabbccddee', 'q9z8y7x6-5w4v-3u2t-1s0r-q9p8o7n6m5l4', 'Monthly Sales Report', 'salesData');
